### ISSUE TITLE
remove moment

### ISSUE THREAD

**Issue by julianosirtori** [aiqfome/aiq-design-system#332]

**Comment by FelipeMaccari** [comment]
uma atualização sobre o react-dates/moment

hoje então ele é uma dependência que ta travando a atualização do react pra nós porque ele usa o Moment como dependencia e foi descontinuado.
eles decidiram que não vão atualizar a lib pro date-fns como era a especulação, ao invés disso eles vão usar  o Temporal que vai sair pro javascript (ta no stage 3 agora)

o Temporal vai trazer funções nativas pra trabalhar com data e horas, aparentemente com a mesma facilidade de um date-fns por exemplo

repo do temporal https://github.com/tc39/proposal-temporal

então ao invés de migrar toda a lib pra uma nova dependência, eles querem deixar tudo javascript nativo, o que eu achei uma baita ideia

essas duas issues da pra ler um pouco o que eles discutiram sobre
https://github.com/airbnb/react-dates/issues/1294
https://github.com/airbnb/react-dates/issues/208
